version: '3'
services:
  api:
    build: .
    command: gunicorn -w 2 -b 0.0.0.0:5000 "api.app:create_app()"
    ports:
      - 5000:5000
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/etc/nginx/html/index.html
      - ./nginx/login.html:/etc/nginx/html/login.html
      - ./nginx/signup.html:/etc/nginx/html/signup.html
      - ./nginx/confirm-acc.html:/etc/nginx/html/confirm-acc.html
      - ./nginx/screener.html:/etc/nginx/html/screener.html
      - ./nginx/dashboard.html:/etc/nginx/html/dashboard.html
      - ./nginx/assets/:/etc/nginx/html/assets/
      